version: 2
jobs:
  build:
    docker:
    - image: circleci/node:11.8-browsers
    steps:
    - checkout # check out source code to working directory
    - restore_cache: # restore the dependency cache
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: install npm dependencies
        command: npm install
    - save_cache: 
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
        - ./node_modules
    - run:
        name: starting a development server
        command: npm run serve
        background: true
    - run: # loop, sleep 0.1 second and check ip 8080 every loop
        name: waiting for server to be responsive
        command: |
            while ! nc -z localhost 8080; do
              sleep 0.1
            done
    - run:
        name: running unit tests
        command: npm run test:unit